// resources/js/react/PerfEmbed.tsx
/**
 * PerfEmbed — React port of the Blade `<x-perf-embed>` component.
 *
 * The Blade component resolves the facade via `EmbedOptimizer` on the
 * server. In React the facade shape must be resolved by the host app (from
 * the server, from build-time data, or from a small fetch) and passed as
 * the `facade` prop. When `facade` is null the component emits nothing;
 * when `lazy=true` it renders a thumbnail + play button that swaps in the
 * real iframe/blockquote on click. Matches the bundled
 * `speculative-rules.js` data-attribute contract so either approach works.
 *
 * @since 1.0.0
 */

import { useMemo, useState, type CSSProperties, type JSX } from 'react';

export type PerfEmbedProvider = 'youtube' | 'vimeo' | 'twitter' | 'x';

export type PerfEmbedMode = 'iframe' | 'blockquote';

export interface PerfEmbedFacade {
	provider: PerfEmbedProvider | string;
	id: string;
	mode: PerfEmbedMode;
	title: string;
	iframe_url: string;
	embed_html: string;
	widgets_script: string;
	thumbnail: string;
}

export interface PerfEmbedProps {
	facade: PerfEmbedFacade | null;
	lazy?: boolean;
	showFacade?: boolean;
	className?: string;
	width?: number;
	height?: number;
	error?: string;
	onActivate?: ( facade: PerfEmbedFacade ) => void;
}

function PlayButton( { title }: { title: string } ): JSX.Element {
	return (
		<button type="button" className="perf-embed-play" aria-label={ title }>
			<svg viewBox="0 0 24 24" width={ 48 } height={ 48 } aria-hidden="true" focusable="false">
				<path d="M8 5v14l11-7z" fill="currentColor" />
			</svg>
		</button>
	);
}

export function PerfEmbed( props: PerfEmbedProps ): JSX.Element | null {
	const { facade, lazy = true, showFacade = true, className, width, height, error, onActivate } = props;
	const [ activated, setActivated ] = useState( false );

	const containerClass = useMemo(
		() => [ 'perf-embed', className ].filter( Boolean ).join( ' ' ),
		[ className ],
	);

	const style: CSSProperties | undefined = useMemo(
		() =>
			undefined !== width && undefined !== height ? { aspectRatio: `${ width } / ${ height }` } : undefined,
		[ width, height ],
	);

	if ( null === facade ) {
		return (
			<>
				{ /* mirrors the Blade `<!-- perf-embed: {reason} -->` no-op */ }
				{ '' !== ( error ?? '' ) ? null : null }
			</>
		);
	}

	const eager = ! lazy;

	if ( eager || activated ) {
		if ( 'blockquote' === facade.mode ) {
			return (
				<div className={ containerClass } style={ style }>
					<div dangerouslySetInnerHTML={ { __html: facade.embed_html } } />
					{ '' !== facade.widgets_script && (
						<script async src={ facade.widgets_script } charSet="utf-8" />
					) }
				</div>
			);
		}
		return (
			<iframe
				src={ facade.iframe_url }
				title={ facade.title }
				loading="eager"
				width={ width }
				height={ height }
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
				referrerPolicy="strict-origin-when-cross-origin"
				allowFullScreen
				className={ containerClass }
			/>
		);
	}

	const activate = (): void => {
		setActivated( true );
		onActivate?.( facade );
	};

	const facadeClass = `${ containerClass } perf-embed-facade`;

	if ( ! showFacade ) {
		return (
			<div
				className={ facadeClass }
				data-provider={ facade.provider }
				data-id={ facade.id }
				data-mode={ facade.mode }
				data-title={ facade.title }
				data-iframe-url={ facade.iframe_url }
				data-widgets-script={ facade.widgets_script }
				style={ style }
				onClick={ activate }
				onKeyDown={ ( event ) => ( 'Enter' === event.key || ' ' === event.key ) && activate() }
				role="button"
				tabIndex={ 0 }
				aria-label={ facade.title }
			/>
		);
	}

	return (
		<div
			className={ facadeClass }
			data-provider={ facade.provider }
			data-id={ facade.id }
			data-mode={ facade.mode }
			data-title={ facade.title }
			data-iframe-url={ facade.iframe_url }
			data-widgets-script={ facade.widgets_script }
			style={ style }
			onClick={ activate }
		>
			{ '' !== facade.thumbnail ? (
				<img
					src={ facade.thumbnail }
					alt={ facade.title }
					loading="lazy"
					decoding="async"
					className="perf-embed-thumbnail"
				/>
			) : (
				<div className="perf-embed-thumbnail perf-embed-thumbnail--placeholder" aria-hidden="true" />
			) }
			<PlayButton title={ facade.title } />
		</div>
	);
}

// resources/js/vue/PerfEmbed.vue
<script setup lang="ts">
/**
 * PerfEmbed — Vue port of the Blade `<x-perf-embed>` component.
 *
 * @since 1.0.0
 */

import { computed, ref } from 'vue';

export type PerfEmbedProvider = 'youtube' | 'vimeo' | 'twitter' | 'x';
export type PerfEmbedMode = 'iframe' | 'blockquote';

export interface PerfEmbedFacade {
	provider: PerfEmbedProvider | string;
	id: string;
	mode: PerfEmbedMode;
	title: string;
	iframe_url: string;
	embed_html: string;
	widgets_script: string;
	thumbnail: string;
}

interface PerfEmbedProps {
	facade: PerfEmbedFacade | null;
	lazy?: boolean;
	showFacade?: boolean;
	className?: string;
	width?: number;
	height?: number;
	error?: string;
}

const props = withDefaults( defineProps<PerfEmbedProps>(), {
	lazy: true,
	showFacade: true,
} );

const emit = defineEmits<{
	( e: 'activate', facade: PerfEmbedFacade ): void;
}>();

const activated = ref( false );

const containerClass = computed( () => [ 'perf-embed', props.className ].filter( Boolean ).join( ' ' ) );

const style = computed( () =>
	undefined !== props.width && undefined !== props.height
		? { aspectRatio: `${ props.width } / ${ props.height }` }
		: undefined,
);

const showEager = computed( () => ! props.lazy || activated.value );

function activate(): void {
	if ( ! props.facade ) {
		return;
	}
	activated.value = true;
	emit( 'activate', props.facade );
}

function onFacadeKey( event: KeyboardEvent ): void {
	if ( 'Enter' === event.key || ' ' === event.key ) {
		activate();
	}
}
</script>

<template>
	<template v-if="props.facade">
		<template v-if="showEager">
			<div v-if="'blockquote' === props.facade.mode" :class="containerClass" :style="style">
				<div v-html="props.facade.embed_html" />
				<script
					v-if="'' !== props.facade.widgets_script"
					async
					:src="props.facade.widgets_script"
					charset="utf-8"
				/>
			</div>
			<iframe
				v-else
				:src="props.facade.iframe_url"
				:title="props.facade.title"
				loading="eager"
				:width="props.width"
				:height="props.height"
				allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
				referrerpolicy="strict-origin-when-cross-origin"
				allowfullscreen
				:class="containerClass"
			/>
		</template>
		<div
			v-else-if="! props.showFacade"
			:class="`${ containerClass } perf-embed-facade`"
			:data-provider="props.facade.provider"
			:data-id="props.facade.id"
			:data-mode="props.facade.mode"
			:data-title="props.facade.title"
			:data-iframe-url="props.facade.iframe_url"
			:data-widgets-script="props.facade.widgets_script"
			:style="style"
			role="button"
			tabindex="0"
			:aria-label="props.facade.title"
			@click="activate"
			@keydown="onFacadeKey"
		/>
		<div
			v-else
			:class="`${ containerClass } perf-embed-facade`"
			:data-provider="props.facade.provider"
			:data-id="props.facade.id"
			:data-mode="props.facade.mode"
			:data-title="props.facade.title"
			:data-iframe-url="props.facade.iframe_url"
			:data-widgets-script="props.facade.widgets_script"
			:style="style"
			@click="activate"
		>
			<img
				v-if="'' !== props.facade.thumbnail"
				:src="props.facade.thumbnail"
				:alt="props.facade.title"
				loading="lazy"
				decoding="async"
				class="perf-embed-thumbnail"
			/>
			<div
				v-else
				class="perf-embed-thumbnail perf-embed-thumbnail--placeholder"
				aria-hidden="true"
			/>
			<button type="button" class="perf-embed-play" :aria-label="props.facade.title">
				<svg viewBox="0 0 24 24" width="48" height="48" aria-hidden="true" focusable="false">
					<path d="M8 5v14l11-7z" fill="currentColor" />
				</svg>
			</button>
		</div>
	</template>
</template>
