// resources/js/react/ResponsiveImage.tsx
/**
 * ResponsiveImage — React port of the Blade `<x-perf-responsive-image>` component.
 *
 * The Blade side resolves srcset values against a filesystem-aware generator.
 * That generator can't run in the browser, so the React port accepts the
 * precomputed AVIF/WebP/fallback srcset strings as props — typically emitted
 * by a build step or a Blade helper on the server and hydrated into the
 * React tree.
 *
 * @since 1.0.0
 */

import type { HTMLAttributes, JSX } from 'react';
import { LazyImage, type LazyImageFetchPriority, type LazyImagePlaceholder } from './LazyImage';

export interface ResponsiveImageProps extends Omit<HTMLAttributes<HTMLElement>, 'placeholder'> {
	src: string;
	alt?: string;
	width?: number;
	height?: number;
	lazy?: boolean;
	placeholder?: LazyImagePlaceholder;
	dominantColor?: string;
	fetchPriority?: LazyImageFetchPriority;
	avifSrcset?: string;
	webpSrcset?: string;
	fallbackSrcset?: string;
	sizesAttr?: string;
	className?: string;
	imgClassName?: string;
}

export function ResponsiveImage( props: ResponsiveImageProps ): JSX.Element {
	const {
		src,
		alt = '',
		width,
		height,
		lazy = true,
		placeholder,
		dominantColor,
		fetchPriority,
		avifSrcset = '',
		webpSrcset = '',
		fallbackSrcset = '',
		sizesAttr,
		className,
		imgClassName,
		...rest
	} = props;

	const combinedClassName = [ 'perf-responsive-image', className ].filter( Boolean ).join( ' ' );

	return (
		<picture { ...rest } className={ combinedClassName }>
			{ '' !== avifSrcset && (
				<source type="image/avif" srcSet={ avifSrcset } sizes={ sizesAttr } />
			) }
			{ '' !== webpSrcset && (
				<source type="image/webp" srcSet={ webpSrcset } sizes={ sizesAttr } />
			) }
			<LazyImage
				src={ src }
				alt={ alt }
				width={ width }
				height={ height }
				lazy={ lazy }
				placeholder={ placeholder }
				dominantColor={ dominantColor }
				fetchPriority={ fetchPriority }
				sizes={ sizesAttr }
				srcSet={ '' !== fallbackSrcset ? fallbackSrcset : undefined }
				className={ imgClassName }
			/>
		</picture>
	);
}

// resources/js/vue/ResponsiveImage.vue
<script setup lang="ts">
/**
 * ResponsiveImage — Vue port of the Blade `<x-perf-responsive-image>`.
 *
 * @since 1.0.0
 */

import { computed } from 'vue';
import LazyImage, { type LazyImageFetchPriority, type LazyImagePlaceholder } from './LazyImage.vue';

interface ResponsiveImageProps {
	src: string;
	alt?: string;
	width?: number;
	height?: number;
	lazy?: boolean;
	placeholder?: LazyImagePlaceholder;
	dominantColor?: string;
	fetchPriority?: LazyImageFetchPriority;
	avifSrcset?: string;
	webpSrcset?: string;
	fallbackSrcset?: string;
	sizesAttr?: string;
	className?: string;
	imgClassName?: string;
}

const props = withDefaults( defineProps<ResponsiveImageProps>(), {
	alt: '',
	lazy: true,
	avifSrcset: '',
	webpSrcset: '',
	fallbackSrcset: '',
} );

const pictureClass = computed( () =>
	[ 'perf-responsive-image', props.className ].filter( Boolean ).join( ' ' ),
);
</script>

<template>
	<picture :class="pictureClass">
		<source
			v-if="'' !== props.avifSrcset"
			type="image/avif"
			:srcset="props.avifSrcset"
			:sizes="props.sizesAttr"
		/>
		<source
			v-if="'' !== props.webpSrcset"
			type="image/webp"
			:srcset="props.webpSrcset"
			:sizes="props.sizesAttr"
		/>
		<LazyImage
			:src="props.src"
			:alt="props.alt"
			:width="props.width"
			:height="props.height"
			:lazy="props.lazy"
			:placeholder="props.placeholder"
			:dominant-color="props.dominantColor"
			:fetch-priority="props.fetchPriority"
			:sizes="props.sizesAttr"
			:srcset="'' !== props.fallbackSrcset ? props.fallbackSrcset : undefined"
			:class-name="props.imgClassName"
		/>
	</picture>
</template>
